### ISSUE TITLE
Campos obligatorios nota de prensa

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#10]
1. Creo nota de prensa
2. Relleno nombre, fecha e intro
3. Guardo

Ocurrido: Guarda nota, lógicamente los links con valor -1
Esperado: Feedback sobre campos obligatorios, no debería poder guardar nota si no tiene tanto PDF como DOC subidos

![screen shot 2015-09-21 at 17 23 01](https://cloud.githubusercontent.com/assets/6526986/9996041/7478df7a-6085-11e5-8bd9-1fff423e59ec.png)

**Comment by juanpablocruz** [comment]
Hecho
