### ISSUE TITLE
Formato fecha publicaciones

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#14]
http://consultorasinmobiliarias.es/index.php?i=18

En Documentos, al filtrar el área, el formato cambia y ya no es "Mes Año" sino "DD/MM/YYY".

![screen shot 2015-09-22 at 23 52 31](https://cloud.githubusercontent.com/assets/6526986/10032723/24c607fe-6185-11e5-8380-178e34b9cb09.png)

**Comment by juanpablocruz** [comment]
Hecho
