### ISSUE TITLE
Campo "descripción" jurado Premios

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#15]
Parece que este campo está recuperando el valor del nombre del jurado en lugar de la descripción. En la bbdd el valor es correcto. Adjunto imagen.

![screen shot 2015-09-23 at 00 02 09](https://cloud.githubusercontent.com/assets/6526986/10032912/7a42c6d0-6186-11e5-88aa-36a6369e2fc8.png)

**Comment by juanpablocruz** [comment]
Esto es lo que te dije que era raro de narices, esto pasa al tener jurados creados y añadir uno nuevo, al guardar el resto se pone el nombre en ambos sitios..sin embargo si editas todos sin añadir ninguno guarda bien.
por tanto hasta que averigüe que narices pasa ahi..me limitaria a recomendar añadir todos los jueces de golpe y con su contenido, ya que los nuevos los guarda bien

**Comment by juanpablocruz** [comment]
Hecho
