### ISSUE TITLE
Edición medios, campos

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#17]
1. Edito medio existente
2. Selecciono prensa escrita
3. Hay un PDF seleccionado

Ocurrido: Me obliga a introducir algún valor en el campo enlace de "Prensa digital" aun siendo "Prensa escrita"
Espeardo: Si es "Prensa escrita", el campo enlace de "Prensa digital" no es mandatory. Debería ocurriy lo mismo en la situación inversa.

**Comment by juanpablocruz** [comment]
Hecho
