### ISSUE TITLE
Al crear nuevo evento, me devuelve un feedback raro (adjunto imagen)

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#2]
![screen shot 2015-09-17 at 14 34 24](https://cloud.githubusercontent.com/assets/6526986/9933159/3fd4dc86-5d49-11e5-98df-092e61e38856.png)

**Comment by juanpablocruz** [comment]
Eso es porque te devuelve una url que no existe, curioso, lo miro
