### ISSUE TITLE
Filtrado imágenes

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#20]
Al filtrar imágenes en galería no se muestran los campos correctos. Sale solamente la fecha (campo que no debería ir incluso). Tomar como referencia los campos que aparecen en las imágenes cuando todavía no se ha filtrado.

![screen shot 2015-09-23 at 00 21 39](https://cloud.githubusercontent.com/assets/6526986/10033325/2cd5019e-6189-11e5-956c-0fc8fd7f54e5.png)

**Comment by juanpablocruz** [comment]
Hecho
