### ISSUE TITLE
Funcionalidad negrita y cursiva para inputs sin formato

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#29]
Igual que el caracter de "#" permite wrapear los textos en naranja en los inputs sin formato, el cliente nos pide el favor de hacer algo parecido para negrita y cursiva.

Las clases de los `<span>` pueden ser "bold" e "italic" pero, como consideres. Los tokens podrían ser `<i>` y `<b>`, por ejemplo.

**Comment by juanpablocruz** [comment]
Hecho
