### ISSUE TITLE
URL incorrecta al filtrar por documento

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#31]
http://consultorasinmobiliarias.es/actividades/publicaciones

Al filtrar por área, añade "actividades" a la URL de cualquier documento, haciendo imposible que se pueda descargar.

De:
http://consultorasinmobiliarias.es/assets/documents/n-1-especial-oficinas.pdf
A:
http://consultorasinmobiliarias.es/actividades/assets/documents/n-1-especial-oficinas.pdf

**Comment by juanpablocruz** [comment]
Hecho
