### ISSUE TITLE
Altura imágenes fondo "Eventos"

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#5]
![screen shot 2015-09-18 at 00 06 40](https://cloud.githubusercontent.com/assets/6526986/9947267/2dde24d8-5d99-11e5-98cd-eeb51e54163f.png)

**Comment by juanpablocruz** [comment]
el js esta bien, lo que esta mal es el css, tienen distintos tamaños, porque quitando la imagen sale tambien distinto
