### ISSUE TITLE
Añadir nuevo campo a Premios

### ISSUE THREAD

**Issue by uncoded** [juanpablocruz/ACI#6]
En el admin, añadir el campo "Archivo inscripción" debajo de "Archivo bases". Mismo formato.

Por otro lado, añadir texto "Descargar formulario" dentro del col-md-3 de inscripción (adjunto imagen de cómo tiene que ir en el código). Vincular aquí el archivo inscripción.

![screen shot 2015-09-18 at 00 47 30](https://cloud.githubusercontent.com/assets/6526986/9947960/fbec5eee-5d9e-11e5-9eb5-7ae040725fd5.png)

**Comment by juanpablocruz** [comment]
Hecho
